# Generated by Django 3.0.10 on 2020-09-15 15:18

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Room Number"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="room_number",
                        verbose_name="Room URL Slug",
                    ),
                ),
                (
                    "room_description",
                    models.TextField(max_length=255, verbose_name="Room Description"),
                ),
                (
                    "room_state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reserved", "Reserved"),
                            ("occupied", "Occupied"),
                            ("unavailable", "Unavailable"),
                            ("out of order", "Out of Order"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Room Status",
                    ),
                ),
            ],
        )
    ]
